package com.jackob101.hms.unittests.service.base;

public enum TestName {
    CREATE_SUCCESSFULLY,
    CREATE_VALIDATION_ERROR,
    CREATE_ID_TAKEN,
    UPDATE_SUCCESSFULLY,
    UPDATE_VALIDATION_ERROR,
    UPDATE_ID_NOT_FOUND,
    UPDATE_ENTITY_NULL,
    FIND_SUCCESSFULLY,
    FIND_ID_NULL,
    FIND_ID_NOT_FOUND,
    DELETE_SUCCESSFULLY,
    DELETE_ID_NULL,
    DELETE_ID_NOT_FOUND,
    DELETE_FAILED;
}
