auth0:
  audience: ${AUTH0_AUDIENCE:}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:}
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
---

spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

---

spring:
  config:
    activate:
      on-profile: mysql
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/hms
    username: root
    password: MPno

---

spring:
  config:
    activate:
      on-profile: debug
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true